_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 77eab84b-6c18-4f9f-816e-cbbf99574110
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /pdf-search
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
